// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFIYyRufABgio9DY4feAB5KjE1ADLWn0E',
    appId: '1:733150686985:web:1cef60b9f670bac515add8',
    messagingSenderId: '733150686985',
    projectId: 'transport-service-a',
    authDomain: 'transport-service-a.firebaseapp.com',
    storageBucket: 'transport-service-a.appspot.com',
    measurementId: 'G-C6RLWHZEHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwNmS5fSCMcY9pf-cgNOeIXNwL7BK6tBY',
    appId: '1:733150686985:android:798032c8de25006a15add8',
    messagingSenderId: '733150686985',
    projectId: 'transport-service-a',
    storageBucket: 'transport-service-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1SQCu1r1CXkyR_mHI4_WOoRf5Se9lhn0',
    appId: '1:733150686985:ios:40e976587ee5e39615add8',
    messagingSenderId: '733150686985',
    projectId: 'transport-service-a',
    storageBucket: 'transport-service-a.appspot.com',
    iosBundleId: 'com.example.transportSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1SQCu1r1CXkyR_mHI4_WOoRf5Se9lhn0',
    appId: '1:733150686985:ios:40e976587ee5e39615add8',
    messagingSenderId: '733150686985',
    projectId: 'transport-service-a',
    storageBucket: 'transport-service-a.appspot.com',
    iosBundleId: 'com.example.transportSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFIYyRufABgio9DY4feAB5KjE1ADLWn0E',
    appId: '1:733150686985:web:799e9c8595f35c7915add8',
    messagingSenderId: '733150686985',
    projectId: 'transport-service-a',
    authDomain: 'transport-service-a.firebaseapp.com',
    storageBucket: 'transport-service-a.appspot.com',
    measurementId: 'G-ZCP6SH9TXX',
  );
}
